export const NameMap: any = {
  overall: 'Overall',
  attack: 'Attack',
  defence: 'Defence',
  strength: 'Strength',
  hitpoints: 'Hitpoints',
  ranged: 'Ranged',
  prayer: 'Prayer',
  magic: 'Magic',
  cooking: 'Cooking',
  woodcutting: 'Woodcutting',
  fletching: 'Fletching',
  fishing: 'Fishing',
  firemaking: 'Firemaking',
  crafting: 'Crafting',
  smithing: 'Smithing',
  mining: 'Mining',
  herblore: 'Herblore',
  agility: 'Agility',
  thieving: 'Thieving',
  slayer: 'Slayer',
  farming: 'Farming',
  runecrafting: 'Runecraft',
  hunter: 'Hunter',
  construction: 'Construction',
  league_points: 'League Points',
  bounty_hunter_hunter: 'Bounty Hunter - Hunter',
  bounty_hunter_rogue: 'Bounty Hunter - Rogue',
  clue_scrolls_all: 'Clue Scrolls (all)',
  clue_scrolls_beginner: 'Clue Scrolls (beginner)',
  clue_scrolls_easy: 'Clue Scrolls (easy)',
  clue_scrolls_medium: 'Clue Scrolls (medium)',
  clue_scrolls_hard: 'Clue Scrolls (hard)',
  clue_scrolls_elite: 'Clue Scrolls (elite)',
  clue_scrolls_master: 'Clue Scrolls (master)',
  last_man_standing: 'LMS - Rank',
  pvp_arena: 'PvP Arena - Rank',
  soul_wars_zeal: 'Soul Wars Zeal',
  guardians_of_the_rift: 'Rifts closed',
  abyssal_sire: 'Abyssal Sire',
  alchemical_hydra: 'Alchemical Hydra',
  artio: 'Artio',
  barrows_chests: 'Barrows Chests',
  bryophyta: 'Bryophyta',
  callisto: 'Callisto',
  calvarion: "Calvar'ion",
  cerberus: 'Cerberus',
  chambers_of_xeric: 'Chambers of Xeric',
  chambers_of_xeric_challenge_mode: 'Chambers of Xeric: Challenge Mode',
  chaos_elemental: 'Chaos Elemental',
  chaos_fanatic: 'Chaos Fanatic',
  commander_zilyana: 'Commander Zilyana',
  corporeal_beast: 'Corporeal Beast',
  crazy_archaeologist: 'Crazy Archaeologist',
  dagannoth_prime: 'Dagannoth Prime',
  dagannoth_rex: 'Dagannoth Rex',
  dagannoth_supreme: 'Dagannoth Supreme',
  deranged_archaeologist: 'Deranged Archaeologist',
  general_graardor: 'General Graardor',
  giant_mole: 'Giant Mole',
  grotesque_guardians: 'Grotesque Guardians',
  hespori: 'Hespori',
  kalphite_queen: 'Kalphite Queen',
  king_black_dragon: 'King Black Dragon',
  kraken: 'Kraken',
  kreearra: "Kree'Arra",
  kril_tsutsaroth: "K'ril Tsutsaroth",
  mimic: 'Mimic',
  nex: 'Nex',
  nightmare: 'Nightmare',
  phosanis_nightmare: "Phosani's Nightmare",
  obor: 'Obor',
  phantom_muspah: 'Phantom Muspah',
  sarachnis: 'Sarachnis',
  scorpia: 'Scorpia',
  skotizo: 'Skotizo',
  spindel: 'Spindel',
  tempoross: 'Tempoross',
  the_gauntlet: 'The Gauntlet',
  the_corrupted_gauntlet: 'The Corrupted Gauntlet',
  theatre_of_blood: 'Theatre of Blood',
  theatre_of_blood_hard_mode: 'Theatre of Blood: Hard Mode',
  thermonuclear_smoke_devil: 'Thermonuclear Smoke Devil',
  tombs_of_amascut: 'Tombs of Amascut',
  tombs_of_amascut_expert: 'Tombs of Amascut: Expert Mode',
  tzkal_zuk: 'TzKal-Zuk',
  tztok_jad: 'TzTok-Jad',
  venenatis: 'Venenatis',
  vetion: "Vet'ion",
  vorkath: 'Vorkath',
  wintertodt: 'Wintertodt',
  zalcano: 'Zalcano',
  zulrah: 'Zulrah'
};
